const products = [
  {
    id: 1,
    nome: "Mini-Frigorífico",
    tipo: "Frio",
    preco: 20,
    duracao: 12,
    imagem: "assets/minifrigorifico.png",
    descricao: "Mini-frigorífico ideal para quartos universitários.",
    caracteristicas: "Capacidade 45L, Silencioso, Termostato ajustável.",
    dimensoes: "45x47x50 cm",
    consumo: "Classe A+",
    datasDisponiveis: ["2026-06-01", "2026-12-31"]
  },
  {
    id: 2,
    nome: "Micro-ondas",
    tipo: "Cozinha",
    preco: 15,
    duracao: 6,
    imagem: "assets/microondas.png",
    descricao: "Micro-ondas compacto e eficiente.",
    caracteristicas: "700W, 20L, 5 níveis de potência.",
    dimensoes: "44x33x26 cm",
    consumo: "800W",
    datasDisponiveis: ["2026-06-15", "2026-09-15"]
  },
  {
    id: 3,
    nome: "Aquecedor",
    tipo: "Climatização",
    preco: 12,
    duracao: 3,
    imagem: "assets/aquecedor.png",
    descricao: "Aquecedor portátil para os meses frios.",
    caracteristicas: "2000W, 2 níveis de aquecimento, Proteção contra sobreaquecimento.",
    dimensoes: "20x15x25 cm",
    consumo: "2000W",
    datasDisponiveis: ["2026-10-01", "2027-03-31"]
  },
  {
    id: 4,
    nome: "Ventoinha",
    tipo: "Climatização",
    preco: 10,
    duracao: 3,
    imagem: "assets/ventoinha.png",
    descricao: "Ventoinha portátil para o verão.",
    caracteristicas: "3 velocidades, Oscilação automática, Silenciosa.",
    dimensoes: "30x30x40 cm",
    consumo: "45W",
    datasDisponiveis: ["2026-05-01", "2026-09-30"]
  },
  {
    id: 5,
    nome: "Máquina de Café Espresso",
    tipo: "Cozinha",
    preco: 8,
    duracao: 1,
    imagem: "assets/maquinacafe.png",
    descricao: "Café de qualidade barista no seu quarto.",
    caracteristicas: "15 bars de pressão, depósito de 1L, bocal de vapor.",
    dimensoes: "20x30x32 cm",
    consumo: "1050W",
    datasDisponiveis: ["2026-06-01", "2026-12-01"]
  },
  {
    id: 6,
    nome: "Aspirador Vertical",
    tipo: "Limpeza",
    preco: 18,
    duracao: 3,
    imagem: "assets/aspirador.png",
    descricao: "Aspirador sem fios, potente e leve.",
    caracteristicas: "Autonomia 40min, Filtro HEPA, Depósito fácil de limpar.",
    dimensoes: "25x15x110 cm",
    consumo: "Bateria Recarregável",
    datasDisponiveis: ["2026-05-20", "2026-11-20"]
  },
  {
    id: 7,
    nome: "Torradeira XL",
    tipo: "Cozinha",
    preco: 5,
    duracao: 1,
    imagem: "assets/torradeiraxl.png",
    descricao: "Torradeira com ranhuras largas para pão rústico.",
    caracteristicas: "7 níveis de tostagem, função descongelar, tabuleiro de migalhas.",
    dimensoes: "30x18x20 cm",
    consumo: "900W",
    datasDisponiveis: ["2026-06-01", "2026-12-31"]
  },
  {
    id: 8,
    nome: "Máquina de Lavar Roupa",
    tipo: "Lavandaria",
    preco: 35,
    duracao: 12,
    imagem: "assets/maquinalavar.png",
    descricao: "Máquina eficiente para poupar nas idas à lavandaria.",
    caracteristicas: "Carga 7kg, 1200rpm, Programas eco.",
    dimensoes: "60x55x85 cm",
    consumo: "Classe A+++",
    datasDisponiveis: ["2026-09-01", "2027-09-01"]
  },
  {
    id: 9,
    nome: "Chaleira Elétrica",
    tipo: "Cozinha",
    preco: 4,
    duracao: 1,
    imagem: "assets/chaleira.png",
    descricao: "Ferve água em segundos para chá ou noodles.",
    caracteristicas: "Capacidade 1.7L, Desligar automático, Filtro anticalcário.",
    dimensoes: "22x15x24 cm",
    consumo: "2200W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 10,
    nome: "Purificador de Ar",
    tipo: "Climatização",
    preco: 15,
    duracao: 6,
    imagem: "assets/purificadorar.png",
    descricao: "Melhore a qualidade do ar no seu espaço de estudo.",
    caracteristicas: "Filtro HEPA H13, sensor de qualidade do ar, modo noturno.",
    dimensoes: "24x24x38 cm",
    consumo: "30W",
    datasDisponiveis: ["2026-06-01", "2026-12-01"]
  },
  {
    id: 11,
    nome: "Fritadeira a Ar (Air Fryer)",
    tipo: "Cozinha",
    preco: 12,
    duracao: 2,
    imagem: "assets/airfryer.png",
    descricao: "Cozinhados saudáveis e rápidos sem óleo.",
    caracteristicas: "Capacidade 4L, Temperatura até 200ºC, 8 programas pré-definidos.",
    dimensoes: "30x30x35 cm",
    consumo: "1500W",
    datasDisponiveis: ["2026-07-01", "2026-11-01"]
  },
  {
    id: 12,
    nome: "Ferro de Engomar a Vapor",
    tipo: "Lavandaria",
    preco: 6,
    duracao: 1,
    imagem: "assets/ferroengomar.png",
    descricao: "Mantenha a sua roupa impecável para apresentações.",
    caracteristicas: "Base cerâmica, jato de vapor 150g, autolimpeza.",
    dimensoes: "30x12x15 cm",
    consumo: "2400W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 13,
    nome: "Desumidificador Compacto",
    tipo: "Climatização",
    preco: 14,
    duracao: 4,
    imagem: "assets/desumidificador.png",
    descricao: "Evite a humidade e o mofo no seu quarto.",
    caracteristicas: "Extração 10L/dia, Depósito 2L, Silencioso.",
    dimensoes: "28x18x48 cm",
    consumo: "210W",
    datasDisponiveis: ["2026-11-01", "2027-03-01"]
  },
  {
    id: 14,
    nome: "Robô Aspirador",
    tipo: "Limpeza",
    preco: 25,
    duracao: 6,
    imagem: "assets/roboaspirador.png",
    descricao: "Limpeza automática enquanto estuda.",
    caracteristicas: "Mapeamento inteligente, App mobile, Retorno automático à base.",
    dimensoes: "33x33x7.5 cm",
    consumo: "Bateria de Lítio",
    datasDisponiveis: ["2026-06-01", "2026-12-31"]
  },
  {
    id: 15,
    nome: "Liquidificador",
    tipo: "Cozinha",
    preco: 7,
    duracao: 1,
    imagem: "assets/liquidificador.png",
    descricao: "Batidos e sumos frescos em segundos.",
    caracteristicas: "Copo de 1.5L, Lâminas de inox, 2 velocidades + Pulse.",
    dimensoes: "18x18x40 cm",
    consumo: "600W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 16,
    nome: "Sanduicheira",
    tipo: "Cozinha",
    preco: 5,
    duracao: 1,
    imagem: "assets/sanduicheira.png",
    descricao: "Snacks rápidos e quentes a qualquer hora.",
    caracteristicas: "Placas antiaderentes, fecho de segurança, luz indicadora.",
    dimensoes: "23x23x9 cm",
    consumo: "750W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 17,
    nome: "Secador de Cabelo Profissional",
    tipo: "Higiene",
    preco: 6,
    duracao: 1,
    imagem: "assets/secador.png",
    descricao: "Secagem rápida e cuidado iónico.",
    caracteristicas: "2200W, 3 níveis temperatura, jato de ar frio.",
    dimensoes: "25x20x10 cm",
    consumo: "2200W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 18,
    nome: "Lâmpada de Estúdio LED",
    tipo: "Escritório",
    preco: 3,
    duracao: 1,
    imagem: "assets/lampadaestudio.png",
    descricao: "Iluminação ideal para longas noites de estudo.",
    caracteristicas: "Braço flexível, 3 tons de luz, entrada USB para carregar telemóvel.",
    dimensoes: "15x15x50 cm",
    consumo: "10W",
    datasDisponiveis: ["2026-05-26", "2027-05-26"]
  },
  {
    id: 19,
    nome: "Mini Forno Elétrico",
    tipo: "Cozinha",
    preco: 12,
    duracao: 3,
    imagem: "assets/fornoeletrico.png",
    descricao: "Para assados e pizzas rápidas.",
    caracteristicas: "Capacidade 20L, Temporizador 60min, Temperatura até 230ºC.",
    dimensoes: "45x32x28 cm",
    consumo: "1380W",
    datasDisponiveis: ["2026-09-01", "2027-01-01"]
  },
  {
    id: 20,
    nome: "Ventoinha de Torre",
    tipo: "Climatização",
    preco: 12,
    duracao: 3,
    imagem: "assets/ventoinhatorre.png",
    descricao: "Oscilação silenciosa e design moderno.",
    caracteristicas: "Altura 80cm, Telecomando, Temporizador.",
    dimensoes: "20x20x80 cm",
    consumo: "50W",
    datasDisponiveis: ["2026-06-01", "2026-09-30"]
  },
];